name: Adding date to changelog.

on:
  release:
    types: [published]

jobs:
  add-date:
    if: "!contains(github.ref, '-rc')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Change changelog file
        run: |
          tag=$(echo $GITHUB_REF | cut -d '/' -f 3)
          sed -i "/## Nuvarande changelog/a \\\n## $tag ($(date -I))" CHANGELOG.md
      - name: Commit
        uses: zwaldowski/git-commit-action@v1
        with:
          commit_message: 'chore: update changelog for release'
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.5.0
        with:
          # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
